name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-push:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    env:
      MAJOR: 1
      MINOR: 0
      PATCH: 0
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Build Image and push to Github Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deploy/docker/Dockerfile
        tags: |
          ghcr.io/pedromsmoreira/sidelogger:${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}.${{ github.run_id }}.${{ github.run_number }}
        push: ${{ github.ref == 'refs/heads/main' }}
    
